Update theme to 2.1.0
sfeir-open-source/sfeir-school-modern-javascript pull request #12
Opened 2020-07-06 19:54 UTC by Xartok

2020-07-07 15:39 UTC, jefBinomed commented
Faudrait splitter certains slides genre 

- slide 19, 20, 21, 22, 29, 37 le passage en 2.1.0 a augmenté la taille des fonts. Du coup faudrait avoir 2 slides
- slide 39, y a trop de code dans le bloc, on doit scroller, il faudrait repenser le code sur ce slide
- slide 42, ça fait bizarre la liste à puce qui mange sur le code, je pense qu'il faudrait supprimer le côté liste à puce.
- slide 44, 59 on ne peut pas scroller ou sélectionner le code... à voir si c'est pas une issue du thème ?
- slide 55, ça serait bien que le lien au milieu soit en text align center 
- slide 60, 106 le texte de l'exercice n'est pas lisible, il y a trop de texte -> voir pour mettre un peu de css perso dans ce cas pour diminuer la taille de font. (via une class, pas en inline ;) )
- slide 75, ça fait bizarre les flèches... c'était comme ça avant ?
- tout ce qui est two_column_layout, faut forcer pour l'instant un margin entre les 2 sections, c'est moche sinon. Et faire ensuite une issue dans le thème avec la proposition de margin associée
- slide 101, doit y avoir des <br> de trop car le texte en bas on ne le voit pas
- slide 118, 119, 121, 122 le texte du code est trop long et nous force à scroller à l'horizontale, il faut faire un retour à la ligne dans ces cas là
- slide 147, il faut surement faire 2 slides car sinon on voit pas le code
- slide 173, il faut scroller, du coup, c'est dommage, il faut repenser le code

2020-07-08 08:49 UTC, jefBinomed requested changes
cf comments :)

2020-07-10 09:40 UTC, Xartok commented
Pour les slides 44, 59 et le two_column_layout j'ai créé les issues sur le repo du theme

2020-07-13 08:37 UTC, jefBinomed requested changes
à voir pourquoi ça fait ça les blocs de code, j'ai l'impression qu'ils ne sont pas en display block...

de même, d'une manière générale sur un two-column-layout, il vaut mieux éviter d'avoir bcp de texte sur le premier slide (celui avec le titre global). Dans ce cas, il vaut mieux mettre le texte dans le slide numéro 1 vertical

2020-07-13 08:37 UTC, jefBinomed commented on docs/markdown/11-Functional-JavaScript/03-pure-functions.md
>  # Fn JS : Pure Functions
![image](https://user-images.githubusercontent.com/681267/87280228-35163900-c4f2-11ea-9491-c519ba511a4c.png)
Soucis avec le slide Fn JS : Haskell


![image](https://user-images.githubusercontent.com/681267/87280117-1152f300-c4f2-11ea-9356-eda359b4c97a.png)
y a un soucis avec le slide Functions as values

2020-07-13 08:37 UTC, jefBinomed commented on docs/markdown/11-Functional-JavaScript/03-pure-functions.md
>  # Fn JS : Pure Functions
![image](https://user-images.githubusercontent.com/681267/87280374-5aa34280-c4f2-11ea-8ebd-699cca3acef8.png)
 Pb avec le slide Fn JS : Quizz 3

2020-07-13 15:17 UTC, jefBinomed approved these changes
+1

2020-07-13 15:22 UTC, merged