Update destructuring and arrays parts
sfeir-open-source/sfeir-school-modern-javascript pull request #14
Opened 2020-07-17 15:38 UTC by Xartok

2020-07-22 14:40 UTC, jefBinomed requested changes
micro modif ^^

2020-07-22 14:40 UTC, jefBinomed commented on docs/markdown/02-closures-variables-hoisting/03-Destructuring-Trailing-commas.md
> +var list = [ 1, 2, 3 ];
à remplacer par let ? ou const

2020-07-22 15:35 UTC, Xartok commented on docs/markdown/02-closures-variables-hoisting/03-Destructuring-Trailing-commas.md
> +var list = [ 1, 2, 3 ];
Il y a beaucoup de cas comme celui-ci, comme je déplaçais juste le texte je n'ai pas corrigé, parce que je compte faire une partie qui harmonise l'utilisation de let/const/var

2020-07-23 09:55 UTC, jefBinomed approved these changes

2020-07-23 10:02 UTC, merged