Update property descriptions and object enhancement part
sfeir-open-source/sfeir-school-modern-javascript pull request #18
Opened 2020-07-23 09:58 UTC by Xartok

2020-07-27 12:21 UTC, jefBinomed requested changes
je changerais un peu ce slide aussi : 
![image](https://user-images.githubusercontent.com/681267/88541029-63c50100-d014-11ea-8add-06a3bf022a51.png)

car je ne le trouve pas clair du tout sur la partie droite du code. On comprends pas ce qu'on doit voir

2020-07-29 06:02 UTC, kuroidoruido commented on docs/markdown/03-property-description-object-enhancements/02-Object.md
> +const newObject = Object.assign(target, object1, object2 );
La nouvelle version est plus clair mais le target sort d'où ? je pense qu'il faut soit créer un objet target juste avant, soit directement mettre objet vide (sans doute moins clair l'objet vide ici)

2020-07-29 22:23 UTC, Xartok commented on docs/markdown/03-property-description-object-enhancements/02-Object.md
> +const newObject = Object.assign(target, object1, object2 );
en effet target n'existe pas ici, c'etait plus conceptuel mais ca vaut le coup de le poser. La présence de target c'est pour avertir que le premier parametre sera modifié. Le plus souvent on utilisera un objet vide.

2020-07-30 05:53 UTC, kuroidoruido commented on docs/markdown/03-property-description-object-enhancements/02-Object.md
> +const newObject = Object.assign(target, object1, object2 );
d'où mon point. Après y'a aussi la possibilité de mettre une phrase indiquant que target est modifié. Voir poser target et indiquer qu'il est modifié. Parce que sinon c'est pas forcément clair pour tout le monde

2020-08-24 17:05 UTC, kuroidoruido approved these changes

2020-08-25 13:31 UTC, jefBinomed approved these changes

2020-08-25 13:31 UTC, jefBinomed commented on docs/markdown/03-property-description-object-enhancements/02-Object.md
> +// puis on récupère l'objet fusionné dans newObject
👍

2022-05-21 14:30 UTC, merged